# Generated by Django 4.0.1 on 2022-01-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=50100)),
                ('price', models.IntegerField()),
                ('room_number', models.CharField(max_length=10000)),
                ('tel_no', models.CharField(default='nonumber', max_length=10000)),
                ('adres', models.CharField(max_length=10000)),
                ('hlatitude', models.CharField(max_length=100000)),
                ('hlongitude', models.CharField(max_length=10000)),
                ('rank', models.FloatField()),
                ('hotel_link', models.CharField(max_length=10000)),
            ],
        ),
    ]
