# Generated by Django 4.0.1 on 2022-01-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostels',
            name='rank',
            field=models.FloatField(max_length=10000),
        ),
    ]
